# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:${OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: 0.0.0.0:${OTEL_COLLECTOR_PORT_HTTP}
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  httpcheck/frontendproxy:
    targets:
      - endpoint: http://frontendproxy:${env:ENVOY_PORT}
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
    operators:
      - type: syslog_parser
        protocol: rfc5424
        body: attributes.message
        resource:
          service:
            name: attributes.appname
  # filelog:
  #   include:
  #     - /var/log/otelcol.json
  #   resource:
  #     host.name: 'localhost'
  #     service.name: 'otel1'
  #   operators:
  #     - type: json_parser
  #       timestamp:
  #         parse_from: attributes.ts
  #         layout_type: epoch
  #         layout: 's.us'
  #       severity:
  #         parse_from: attributes.level
  #       body: attributes.msg

exporters:
  debug:
  otlphttp/prometheus:
    endpoint: "http://victoriametrics:8428/api/v1/write"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
    tls:
      insecure: true
    # target_info:
    #   enabled: true # metric is generated for each resource metric
    # resource_to_telemetry_conversion:
    #   enabled: true # convert resource attributes to metric labels
  opensearch:
    logs_index: otel
    http:
      endpoint: "http://opensearch:9200"
      tls:
        insecure: true
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    ttl_days: 3
    traces_table_name: otel_traces
    logs_table_name: otel_logs
    timeout: 5s
    database: default
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:

connectors:
  spanmetrics:
    dimensions:
      - name: http.method
      - name: http.status_code
      - name: http.route

service:
  telemetry:
    logs:
      level: INFO
      encoding: json
      # output_paths: /var/log/otelcol.json
      # error_output_paths: /var/log/otelcol.json
    metrics:
      level: detailed
      address: 0.0.0.0:8888
    traces:
      processors:
        batch:
          exporter:
            otlp:
              protocol: grpc/protobuf
              endpoint: localhost:4317

  pipelines:
    # traces:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [debug, spanmetrics, clickhouse]
    # metrics:
    #   receivers: [httpcheck/frontendproxy, otlp]
    #   processors: [batch]
    #   exporters: [otlphttp/prometheus, debug]
    logs:
      receivers: [otlp, syslog]
      processors: [batch]
      exporters: [clickhouse, debug]
    # metrics/spanmetrics:
    #   receivers: [spanmetrics]
    #   processors: [batch]
    #   exporters: [prometheusremotewrite, debug]
